Add statenotifier (Create StateNotifier template)
tbm98/flutter-riverpod-live-templates pull request #1
Opened 2020-10-07 18:21 UTC by HugoHeneault

It isn't from Riverpod but I use this one quite often and I think it is missing here :-)

2020-10-07 18:27 UTC, HugoHeneault commented
Or maybe we can update `StateNotifierProvider` snippet to create the StateNotifier and its Provider?

```
class $name$Notifier extends StateNotifier<$result$> {
  $name$Notifier(): super($initialState$);

  $END$
}

final $name$Provider = StateNotifierProvider<$name$Notifier>((ref) => $name$Notifier());

```

2020-10-09 14:23 UTC, tbm98 commented
I think we should just create each of them independently.

2020-10-09 14:27 UTC, tbm98 requested changes

2020-10-09 14:27 UTC, tbm98 commented on src/main/resources/liveTemplates/Flutter_riverpod_snippets.xml
> +      <option name="DART" value="true" />
It should be set to `DART_TOPLEVEL` scope.

2020-10-09 18:33 UTC, HugoHeneault commented
Also would you add the `hacktoberfest` topic to this repo saying that you allows other devs to contribute to your repo while [participating](https://hacktoberfest.digitalocean.com/) to it?

Thanks :)

2020-10-10 11:43 UTC, tbm98 approved these changes
Great!

2020-10-10 11:45 UTC, merged

2020-10-10 11:47 UTC, tbm98 commented
> Also would you add the `hacktoberfest` topic to this repo saying that you allows other devs to contribute to your repo while [participating](https://hacktoberfest.digitalocean.com/) to it?

How to apply it ?

2020-10-10 12:30 UTC, HugoHeneault commented
> > Also would you add the `hacktoberfest` topic to this repo saying that you allows other devs to contribute to your repo while [participating](https://hacktoberfest.digitalocean.com/) to it?
> 
> How to apply it ?

They say "Maintainers can opt-in to participate by classifying their projects with the `hacktoberfest` topic.", it's on the main page in the about section:

![image](https://user-images.githubusercontent.com/4112256/95655079-23e6c380-0b05-11eb-9ab4-a46ebc89177f.png)

2020-10-10 14:11 UTC, tbm98 commented
Yes. I will try it 😁

Vào 19:30, Th 7, 10 thg 10, 2020 Hugo Heneault <notifications@github.com>
đã viết:

> Also would you add the hacktoberfest topic to this repo saying that you
> allows other devs to contribute to your repo while participating
> <https://hacktoberfest.digitalocean.com/> to it?
>
> How to apply it ?
>
> They say "Maintainers can opt-in to participate by classifying their
> projects with the hacktoberfest topic.", it's on the main page in the
> about section:
>
> [image: image]
> <https://user-images.githubusercontent.com/4112256/95655079-23e6c380-0b05-11eb-9ab4-a46ebc89177f.png>
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/tbm98/flutter-riverpod-live-templates/pull/1#issuecomment-706541965>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMRATJDBGZN75ZNKHZDHHADSKBHYHANCNFSM4SHX2T7A>
> .
>